# replace weights_directory with either:
# * the *ABSOLUTE PATH* to where you store your weights, or
# * the huggingface repo with your weights
[llama-13b]
weights_directory = /share/u/smarks/llama_from_lambda/13B
name = LLaMA-13B
probe_layer = 13
intervene_layer = 7
noperiod = False
[llama-2-13b]
weights_directory = meta-llama/Llama-2-13b-hf
name = LLaMA-2-13B
probe_layer = 14
intervene_layer = 8
noperiod = False
[llama-2-70b]
weights_directory = meta-llama/Llama-2-70b-hf
name = LLaMA-2-13B
intervene_layer = 8
probe_layer = 27
noperiod = False

[llama-2-7b]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Llama-2-7b-hf
name = LLaMA-2-7B
probe_layer = 13
intervene_layer = 8
noperiod = False

[llama-3-1B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Llama-3-1B-Instruct
name = LLama-3-1B
probe_layer_a = 3 #18
probe_layer_b = 6 #18 
probe_layer_c = 11 #18
probe_layer_d = 15 #18
noperiod = False

[llama-3-3B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Llama-3-3B-Instruct
name = LLama-3-3B
probe_layer_a = 1 #18
probe_layer_b = 7 #18 
probe_layer_c = 19#18
probe_layer_d = 27 #18
noperiod = False

[llama-3-8B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Llama-3-8B-Instruct
name = LLama-3-8B
probe_layer_a = 3 #18
probe_layer_b = 10 #18 
probe_layer_c = 22 #18
probe_layer_d = 31 #18
noperiod = False

[llama-3-70B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Llama-3-70B-Instruct
name = LLama-3-70B
probe_layer_a = 0 #18
probe_layer_b = 38 #18 
probe_layer_c = 52 #18
probe_layer_d = 78 #18
noperiod = False

[llama-2-13b-reset]
weights_directory = meta-llama/Llama-2-13b-hf
name = LLaMA-2-13B-reset
probe_layer = 14
intervene_layer = 8
noperiod = False

[Qwen2.5-72B-Instruct]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen2.5-72B-Instruct
name = Qwen2.5-72B-Instruct
probe_layer = 14
intervene_layer = 8
noperiod = False

[gemma-3-27b-it]
weights_directory = /Users/giulianowietig/PycharmProjects/models/gemma-3-27b-it
name = gemma-3-27b-it
probe_layer_a = 4 #18
probe_layer_b = 11 #18 
probe_layer_c = 34#18
probe_layer_d = 61 #18
intervene_layer_a = 0
intervene_layer_b1 = 20
intervene_layer_b2 = 21
intervene_layer_c = 32
noperiod = False

[Mistral-small]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Mistral-small-2506
name = Mistral-Small-3.2-24B-Instruct-2506
probe_layer = 14
intervene_layer = 8
noperiod = False

[gpt-oss-120b]
weights_directory = /Users/giulianowietig/PycharmProjects/models/gpt-oss-120b
name = gpt-oss-120b

[bert-base-uncased]
weights_directory = /Users/giulianowietig/PycharmProjects/models/bert-base-uncased
name = bert-base-uncased
probe_layer = 4
intervene_layer = 2
noperiod = False

[HateBERT]
weights_directory = /Users/giulianowietig/PycharmProjects/models/HateBERT
name = HateBERT
probe_layer = 4
intervene_layer = 2
noperiod = False

[ModernBERT-base]
weights_directory = /Users/giulianowietig/PycharmProjects/models/ModernBERT-base
name = ModernBERT-base
probe_layer_a = 4
probe_layer_b = 14
probe_layer_c = 21
intervene_layer = 2
noperiod = False

[deBERTa-v3-base]
weights_directory = /Users/giulianowietig/PycharmProjects/models/deBERTa-v3-base
name = deBERTa-v3-base
probe_layer = 4
intervene_layer = 2
noperiod = False

[roberta-large]
weights_directory = /Users/giulianowietig/PycharmProjects/models/roberta-large
name = roberta-large
probe_layer_a = 4
probe_layer_b = 14
probe_layer_c = 23
intervene_layer = 2
noperiod = False

[roberta-base]
weights_directory = /Users/giulianowietig/PycharmProjects/models/roberta-base
name = roberta-base
probe_layer_a = 3
probe_layer_b = 7
probe_layer_c = 11
intervene_layer_a = 0
intervene_layer_b = 6
noperiod = False

[roberta-non-knowledge-v1-base]
weights_directory = /Users/giulianowietig/PycharmProjects/models/roberta-non-knowledge-v1-base
name = roberta-non-knowledge-v1-base
probe_layer_a = 3
probe_layer_b = 7
probe_layer_c = 11
intervene_layer_a = 0
intervene_layer_b = 6
noperiod = False

[roberta-non-knowledge-v8-base]
weights_directory = /Users/giulianowietig/PycharmProjects/models/roberta-non-knowledge-v8-base
name = roberta-non-knowledge-v8-base
probe_layer_a = 3
probe_layer_b = 7
probe_layer_c = 11
intervene_layer_a = 0
intervene_layer_b = 6
noperiod = False

[roberta-non-knowledge-v2-base]
weights_directory = /Users/giulianowietig/PycharmProjects/models/roberta-non-knowledge-v2-base
name = roberta-non-knowledge-v2-base
probe_layer_a = 3
probe_layer_b = 7
probe_layer_c = 11
intervene_layer_a = 0
intervene_layer_b = 6
noperiod = False

[roberta-non-knowledge-v1-large]
weights_directory = /Users/giulianowietig/PycharmProjects/models/roberta-non-knowledge-v1-large
name = roberta-non-knowledge-v1-large
probe_layer_a = 4
probe_layer_b = 14
probe_layer_c = 23
intervene_layer_a = 0
intervene_layer_b = 6
noperiod = False

[roberta-non-knowledge-v8-large]
weights_directory = /Users/giulianowietig/PycharmProjects/models/roberta-non-knowledge-v8-large
name = roberta-non-knowledge-v8-large
probe_layer_a = 4
probe_layer_b = 14
probe_layer_c = 23
intervene_layer_a = 0
intervene_layer_b = 6
noperiod = False

[roberta-non-knowledge-v2-large]
weights_directory = /Users/giulianowietig/PycharmProjects/models/roberta-non-knowledge-v2-large
name = roberta-non-knowledge-v2-large
probe_layer_a = 4
probe_layer_b = 14
probe_layer_c = 23
intervene_layer_a = 0
intervene_layer_b = 6
noperiod = False

[ModernBERT-non-knowledge-v1]
weights_directory = /Users/giulianowietig/PycharmProjects/models/ModernBERT-non-knowledge-v1
name = ModernBERT-non-knowledge-v1
probe_layer_a = 4
probe_layer_b = 14
probe_layer_c = 21
intervene_layer_a = 0
intervene_layer_b = 6
noperiod = False

[ModernBERT-non-knowledge-v2]
weights_directory = /Users/giulianowietig/PycharmProjects/models/ModernBERT-non-knowledge-v2
name = ModernBERT-non-knowledge-v2
probe_layer_a = 4
probe_layer_b = 14
probe_layer_c = 21
intervene_layer_a = 0
intervene_layer_b = 6
noperiod = False

[ModernBERT-non-knowledge-v8]
weights_directory = /Users/giulianowietig/PycharmProjects/models/ModernBERT-non-knowledge-v8
name = ModernBERT-non-knowledge-v8
probe_layer_a = 4
probe_layer_b = 14
probe_layer_c = 21
intervene_layer_a = 0
intervene_layer_b = 6
noperiod = False

[roberta-toxicity]
weights_directory = /Users/giulianowietig/PycharmProjects/models/roberta-toxicity
name = roberta-large
probe_layer_a = 5
probe_layer_b = 11
intervene_layer_a = 0
intervene_layer_b = 6
noperiod = False

[Qwen3-32B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-32B
name = Qwen3-32B
probe_layer_a = 6
probe_layer_b = 26 #19
probe_layer_c = 50
probe_layer_d = 63 
intervene_layer_a = 0
intervene_layer_b1 = 35
intervene_layer_b2 = 43
intervene_layer_c = 49
noperiod = False

[Qwen3-30B-A3B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-30B-A3B
name = Qwen3-30B-A3B
probe_layer_a = 6
probe_layer_b = 20 #19
probe_layer_c = 30
probe_layer_d = 47 
noperiod = False

[Qwen3-14B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-14B
name = Qwen3-14B
probe_layer_a = 4
probe_layer_b = 10 #19
probe_layer_c = 25
probe_layer_d = 39 
intervene_layer_a = 0
intervene_layer_b = 11
intervene_layer_c = 20
intervene_layer_d = 25
noperiod = False

[Qwen3-8B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-8B
name = Qwen3-8B
probe_layer_a = 2 #18
probe_layer_b = 9 #18
probe_layer_c = 22 #18
probe_layer_d = 35 #18
intervene_layer_a = 0
intervene_layer_b1 = 7
intervene_layer_b2 = 10
intervene_layer_c = 21
noperiod = False

[Qwen3-4B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-4B
name = Qwen3-4B
probe_layer_a = 2 #15, 17
probe_layer_b = 9 #18
probe_layer_c = 22 #18
probe_layer_d = 35 #18
intervene_layer_a = 0
intervene_layer_b1 = 7
intervene_layer_b2 = 17
intervene_layer_c = 20
noperiod = False

[Qwen3-1_7B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-1_7B
name = Qwen3-1.7B
probe_layer_a = 3 #18
probe_layer_b = 6 #18
probe_layer_c = 18 #18
probe_layer_d = 27 #18
intervene_layer_a = 0
intervene_layer_b1 = 7
intervene_layer_b2 = 12
intervene_layer_c = 17
noperiod = False

[Qwen3-0_6B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-0_6B
name = Qwen3-0_6B
probe_layer_a = 1 #18
probe_layer_b = 4 #18
probe_layer_c = 17 #18
probe_layer_d = 27 #18
intervene_layer_a = 0
intervene_layer_b1 = 7
intervene_layer_b2 = 11
intervene_layer_c = 17
noperiod = False

[Qwen-1_8B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen-1_8B
name = Qwen-1_8B
probe_layer_a = 1 #18
probe_layer_b = 4 #18
probe_layer_c = 17 #18
probe_layer_d = 27 #18
noperiod = False

[Qwen1_5-1_8B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen1_5-1_8B
name = Qwen1_5-1_8B
probe_layer_a = 1 #18
probe_layer_b = 4 #18
probe_layer_c = 17 #18
probe_layer_d = 23 #18
noperiod = False

[Qwen2-1_5B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen2-1_5B
name = Qwen2-1_5B
probe_layer_a = 1 #18
probe_layer_b = 4 #18
probe_layer_c = 17 #18
probe_layer_d = 27 #18
noperiod = False

[Qwen2_5-1_5B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen2_5-1_5B
name = Qwen2_5-1_5B
probe_layer_a = 1 #18
probe_layer_b = 4 #18
probe_layer_c = 17 #18
probe_layer_d = 27 #18
noperiod = False

[gemma-3-12b-it]
weights_directory = /Users/giulianowietig/PycharmProjects/models/gemma-3-12b-it
name = gemma-3-12b-it
probe_layer_a = 4 #18
probe_layer_b = 10 #18
probe_layer_c = 27 #18
probe_layer_d = 47 #18
intervene_layer_a = 0
intervene_layer_b1 = 13
intervene_layer_b2 = 14
intervene_layer_c = 25
noperiod = False

[gemma-3-4b-it]
weights_directory = /Users/giulianowietig/PycharmProjects/models/gemma-3-4b-it
name = gemma-3-4b-it
probe_layer_a = 2 #18
probe_layer_b = 9 #18 
probe_layer_c = 22#18
probe_layer_d = 33 #18
intervene_layer_a = 0
intervene_layer_b1 = 10
intervene_layer_b2 = 6
intervene_layer_c = 15 
noperiod = False

[gemma-3-1b-it]
weights_directory = /Users/giulianowietig/PycharmProjects/models/gemma-3-1b-it
name = gemma-3-1b-it
probe_layer_a = 3 #18
probe_layer_b = 10 #18 
probe_layer_c = 15 #18
probe_layer_d = 25 #18
intervene_layer_a = 0
intervene_layer_b1 = 9
intervene_layer_b2 = 12
intervene_layer_c = 13
noperiod = False

[gemma-3-270m-it]
weights_directory = /Users/giulianowietig/PycharmProjects/models/gemma-3-270m-it
name = gemma-3-270m-it
probe_layer_a = 1 #18
probe_layer_b = 5 #18
probe_layer_c = 12 #18
probe_layer_d = 17 #18
intervene_layer_a = 0
intervene_layer_b1 = 6
intervene_layer_b2 = 6
intervene_layer_c = 9
noperiod = False

[Phi-4]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Phi-4
name = Phi-4
probe_layer = 14
intervene_layer = 8
noperiod = False

[Phi-4-mini]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Phi-4-mini
name = Phi-4-mini
probe_layer = 14
intervene_layer = 8
noperiod = False