# replace weights_directory with either:
# * the *ABSOLUTE PATH* to where you store your weights, or
# * the huggingface repo with your weights

[Qwen3-32B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-32B
name = Qwen3-32B
probe_layer_a = 5 #12
probe_layer_b = 26 #26 #19
probe_layer_c = 41 #30
probe_layer_d = 63 #55
noperiod = False

[Qwen3-14B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-14B
name = Qwen3-14B
probe_layer_a = 6 #8
probe_layer_b = 18 #14 #19
probe_layer_c = 26 #22
probe_layer_d = 39 
noperiod = False

[Qwen3-8B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-8B
name = Qwen3-8B
probe_layer_a = 3 #4
probe_layer_b = 15 #19
probe_layer_c = 27
probe_layer_d = 35
noperiod = False

[Qwen3-4B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-4B
name = Qwen3-4B
probe_layer_a = 4 #3
probe_layer_b = 9 #9 #19
probe_layer_c = 17 #18
probe_layer_d = 35 #30
noperiod = False

[Qwen3-1_7B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-1_7B
name = Qwen3-1.7B
probe_layer_a = 3 #4
probe_layer_b = 8 #12 #19
probe_layer_c = 12 #16
probe_layer_d = 27 #25
noperiod = False

[Qwen3-0_6B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-0_6B
name = Qwen3-0_6B
probe_layer_a = 3 #3
probe_layer_b = 7 #19
probe_layer_c = 19 #17
probe_layer_d = 27 #26
noperiod = False

[gemma-3-27b-it]
weights_directory = /Users/giulianowietig/PycharmProjects/models/gemma-3-27b-it
name = gemma-3-27b-it
probe_layer_a = 8 #13
probe_layer_b = 18 #19
probe_layer_c = 32 #42
probe_layer_d = 61 #51
noperiod = False

[gemma-3-12b-it]
weights_directory = /Users/giulianowietig/PycharmProjects/models/gemma-3-12b-it
name = gemma-3-12b-it
probe_layer_a = 4 #9
probe_layer_b = 15 #16 #19
probe_layer_c = 27 #27
probe_layer_d = 47 #40
noperiod = False

[gemma-3-4b-it]
weights_directory = /Users/giulianowietig/PycharmProjects/models/gemma-3-4b-it
name = gemma-3-4b-it
probe_layer_a = 5 #2
probe_layer_b = 9 #13 #19
probe_layer_c = 20 #23
probe_layer_d = 33 #28
noperiod = False

[gemma-3-1b-it]
weights_directory = /Users/giulianowietig/PycharmProjects/models/gemma-3-1b-it
name = gemma-3-1b-it
probe_layer_a = 5 #2
probe_layer_b = 13 #6 #19
probe_layer_c = 18 #12
probe_layer_d = 25 #18
noperiod = False

[gemma-3-270m-it]
weights_directory = /Users/giulianowietig/PycharmProjects/models/gemma-3-270m-it
name = gemma-3-270m-it
probe_layer_a = 5 #1
probe_layer_b = 21 #5 #19
probe_layer_c = 27
probe_layer_d = 33 #16
noperiod = False