# replace weights_directory with either:
# * the *ABSOLUTE PATH* to where you store your weights, or
# * the huggingface repo with your weights

[llama-3-1B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Llama-3-1B-Instruct
name = LLama-3-1B
last_layer = 15 #18
noperiod = False

[llama-3-3B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Llama-3-3B-Instruct
name = LLama-3-3B
last_layer = 27 #18
noperiod = False

[llama-3-8B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Llama-3-8B-Instruct
name = LLama-3-8B
last_layer = 31 #18
noperiod = False

[Qwen3-32B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-32B
name = Qwen3-32B
last_layer = 63 
noperiod = False

[Qwen3-30B-A3B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-30B-A3B
name = Qwen3-30B-A3B
last_layer = 47 
noperiod = False

[Qwen3-14B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-14B
name = Qwen3-14B
last_layer = 39 
noperiod = False

[Qwen3-8B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-8B
name = Qwen3-8B
last_layer = 35 #18
noperiod = False

[Qwen3-4B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-4B
name = Qwen3-4B
last_layer = 35 #18
noperiod = False

[Qwen3-1_7B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-1_7B
name = Qwen3-1.7B
last_layer = 27 #18
noperiod = False

[Qwen3-0_6B]
weights_directory = /Users/giulianowietig/PycharmProjects/models/Qwen3-0_6B
name = Qwen3-0_6B
last_layer = 27 #18
noperiod = False